services:
  - type: web
    name: attendance-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/test-route
    autoDeploy: true
    envVars:
      # Pin Python to a version compatible with mediapipe/tflite-runtime
      - key: PYTHON_VERSION
        value: "3.10.13"

      # Fill these on Render Dashboard (kept out of source using sync:false)
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        sync: false
      - key: SEED_GOV_ADMIN_EMAIL
        sync: false
      - key: SEED_GOV_ADMIN_NAME
        sync: false
      - key: SEED_GOV_ADMIN_PASSWORD
        sync: false
